const mysql = require('mysql2/promise');
const bcrypt = require('bcrypt');

const fullStudentsRaw = `
7376231EC212	MIDUN THANIGACHALAM SUBBARAYAN	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. KARTHIKEYAN S ECE
7376231EC213	MITHUN B S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. KARTHIKEYAN S ECE
7376231EC214	MOHAMED ISMAIL T	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. KARTHIKEYAN S ECE
7376231EC215	MOHAMMAD ABDULLAH S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. KARTHIKEYAN S ECE
7376231EC216	MOHAMMED HANIFA M	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. KARTHIKEYAN S ECE
7376231EC217	MOHAMMED HUSSAIN F	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. KARTHIKEYAN S ECE
7376231EC218	MOHIT BALAJI M	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. KARTHIKEYAN S ECE
7376231EC219	MONIKA M	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. KARTHIKEYAN S ECE
7376231EC220	MONIKA SRI K	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. KARTHIKEYAN S ECE
7376231EC221	MONISH R	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. SARANYA N ECE
7376231EC222	MUGESHKANNA S R	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. SARANYA N ECE
7376231EC223	NANDHA VISVANATHAN	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. ARUN KUMAR R AIDS
7376231EC224	NANTHANA C	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. SARANYA N ECE
7376231EC225	NARBAVI T	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. SARANYA N ECE
7376231EC226	NARESH S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. SARANYA N ECE
7376231EC227	NAVEEN KUMAR I	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. SARANYA N ECE
7376231EC228	NAVEEN KUMAR K V	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. SARANYA N ECE
7376231EC229	NAVEENA K	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. SARANYA N ECE
7376231EC230	NIKHITHA M	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. SARANYA N ECE
7376231EC231	NISAR DEEN N	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. SARANYA N ECE
7376231EC232	NITHESH S J	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. SARANYA N ECE
7376231EC233	OVIYA S S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. SARANYA N ECE
7376231EC234	PALANI MURUGAN L	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. SARANYA N ECE
7376231EC235	POORVIKA M S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. SARANYA N ECE
7376231EC236	PRADEEPRAJ R	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. SARANYA N ECE
7376231EC237	PRAKADEESH N	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. SARANYA N ECE
7376231EC238	PRAKATHI J	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. SARANYA N ECE
7376231EC240	PRANESH S R	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. SARANYA N ECE
7376231EC241	PRASAD R	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. RAJA SEKAR S ECE
7376231EC242	PRASANNAVADHANA V	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. RAJA SEKAR S ECE
7376231EC243	PRASANTH P	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. RAJA SEKAR S ECE
7376231EC244	PRASANTH S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. RAJA SEKAR S ECE
7376231EC245	PRAVEENKUMAR K	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. RAJA SEKAR S ECE
7376231EC246	PRAVEENSANDOSH NAGARAJAN N	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. RAJA SEKAR S ECE
7376231EC247	PREETHI S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. RAJA SEKAR S ECE
7376231EC250	RAGUL V	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. RAJA SEKAR S ECE
7376231EC251	RAHUL B	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. RAJA SEKAR S ECE
7376231EC252	RAJ KUMAR R	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. RAJA SEKAR S ECE
7376231EC253	RASHMI R	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. RAJA SEKAR S ECE
7376231EC254	RATNADEEPA K P	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. RAJA SEKAR S ECE
7376231EC255	RENUGADEVI S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. RAJA SEKAR S ECE
7376231EC256	RITHIKA P	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. RAJA SEKAR S ECE
7376231EC257	RITHIN R S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. RAJA SEKAR S ECE
7376231EC258	RITHISH M	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. RAJA SEKAR S ECE
7376231EC259	RITIKA DEVI M K	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. RAJA SEKAR S ECE
7376231EC260	ROHITH SRIRAM M	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. RAJA SEKAR S ECE
7376231EC261	RUPAHARINI M	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. BARANIDHARAN V ECE
7376231EC262	SABARISH R	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. BARANIDHARAN V ECE
7376231EC263	SABARISH R T	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. BARANIDHARAN V ECE
7376231EC265	SAISRIHARAN S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. BARANIDHARAN V ECE
7376231EC266	SAKTHI DHARSHAN S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. BARANIDHARAN V ECE
7376231EC267	SAMEETHA P	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. BARANIDHARAN V ECE
7376231EC268	SANJAI SHYAM D S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. BARANIDHARAN V ECE
7376231EC269	SANJAY GANDHI G	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. BARANIDHARAN V ECE
7376231EC270	SANJAY SRI THANU MALAIYAAN C	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. BARANIDHARAN V ECE
7376231EC271	SANJEI A K	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. BARANIDHARAN V ECE
7376231EC272	SANTHOSH M	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. BARANIDHARAN V ECE
7376231EC273	SASIRITHIKA S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. BARANIDHARAN V ECE
7376231EC274	SATHISH KUMAR R	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. BARANIDHARAN V ECE
7376231EC275	SATHISH S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. BARANIDHARAN V ECE
7376231EC276	SAVEETHA S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. BARANIDHARAN V ECE
7376231EC277	SHAAJITH R	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. BARANIDHARAN V ECE
7376231EC278	SHANUSH	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. BARANIDHARAN V ECE
7376231EC279	SHARAN V	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. BARANIDHARAN V ECE
7376231EC280	SHARUN AKASH P	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mr. BARANIDHARAN V ECE
7376231EC281	SHRINIDHI J	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. MYTHILI S ECE
7376231EC282	SHRINITHI S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. MYTHILI S ECE
7376231EC284	SIVA LAVANYA S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. MYTHILI S ECE
7376231EC285	SIVANI S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. MYTHILI S ECE
7376231EC286	SIVASHANKARI R	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. MYTHILI S ECE
7376231EC287	SIVASUBRAMANIYAM S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. MYTHILI S ECE
7376231EC288	SRI HARIHARAN V	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. MYTHILI S ECE
7376231EC289	SRI NIVITHA S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. MYTHILI S ECE
7376231EC290	SRI RAGUL A A	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. MYTHILI S ECE
7376231EC291	SRINIDHI J	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. MYTHILI S ECE
7376231EC292	SUBASH CHANDRABOSE M	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. MYTHILI S ECE
7376231EC293	SUBHASHINI N	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. MYTHILI S ECE
7376231EC294	SUBIKSHA K P	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. MYTHILI S ECE
7376231EC295	SUBIKSHA SHREE S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. MYTHILI S ECE
7376231EC296	SUBITHA S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. MYTHILI S ECE
7376231EC297	SUGANTHAN S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. MYTHILI S ECE
7376231EC298	SUGANTHAN S V	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. MYTHILI S ECE
7376231EC299	SUGANYA K	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. MYTHILI S ECE
7376231EC300	SUGASHINI M	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. MYTHILI S ECE
7376231EC301	SUJITH MOHANASUNDARAM SUMATHI	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. NALIFABEGAM J ECE
7376231EC302	SURYA S V	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. NALIFABEGAM J ECE
7376231EC303	SURYANARAYANA B G	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. NALIFABEGAM J ECE
7376231EC304	SUTHAN S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. NALIFABEGAM J ECE
7376231EC306	THANMATHI V	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. NALIFABEGAM J ECE
7376231EC307	THARUN ADHITHYA S K	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. NALIFABEGAM J ECE
7376231EC308	THARUN PRASATH C	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. NALIFABEGAM J ECE
7376231EC309	THIANESWAR K R	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. NALIFABEGAM J ECE
7376231EC310	TRISHNA R	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. NALIFABEGAM J ECE
7376231EC311	VAISHNAVI B	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. NALIFABEGAM J ECE
7376231EC312	VAISHNAVI S K	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. NALIFABEGAM J ECE
7376231EC313	VARSHIKA S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. NALIFABEGAM J ECE
7376231EC315	VENKATESH K	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. NALIFABEGAM J ECE
7376231EC316	VIBIN V	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. NALIFABEGAM J ECE
7376231EC317	VIDULA SANJANA S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. NALIFABEGAM J ECE
7376231EC319	VIGNESHWARAN M	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. NALIFABEGAM J ECE
7376231EC320	VIJAY T	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. NALIFABEGAM J ECE
7376231EC321	VIKASH T	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. LEEBAN MOSES M ECE
7376231EC322	VIMAL KUMAR P	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. LEEBAN MOSES M ECE
7376231EC323	VIMAL V	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. LEEBAN MOSES M ECE
7376231EC324	VISALINI S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. LEEBAN MOSES M ECE
7376231EC325	VISHAL R	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. LEEBAN MOSES M ECE
7376231EC326	VISHAL S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. LEEBAN MOSES M ECE
7376231EC327	VISHAL T	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. LEEBAN MOSES M ECE
7376231EC328	VISHNU N	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. LEEBAN MOSES M ECE
7376231EC329	VISHNU RAJ P S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. LEEBAN MOSES M ECE
7376231EC330	VISHRUTHA G E	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. LEEBAN MOSES M ECE
7376231EC331	VISHVANTH S S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. LEEBAN MOSES M ECE
7376231EC332	VRLRAINA E	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. LEEBAN MOSES M ECE
7376231EC333	YASHWENTH RAJ G	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. LEEBAN MOSES M ECE
7376231EC334	YOGAGOWTHAM R	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. LEEBAN MOSES M ECE
7376241EC501	AHARSHAN D	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. LEEBAN MOSES M ECE
7376241EC502	ASHOK J	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. LEEBAN MOSES M ECE
7376241EC503	BHARATH A	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. LEEBAN MOSES M ECE
7376241EC504	DHANUSH J B	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. LEEBAN MOSES M ECE
7376241EC505	DHARANI DHARAN K	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. LEEBAN MOSES M ECE
7376241EC506	GIRIRAJ A	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. LEEBAN MOSES M ECE
7376241EC507	GOKUL NATHAN M	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. ARULMURUGAN L ECE
7376241EC508	GOPI CHARAN N	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. ARULMURUGAN L ECE
7376241EC509	INDHUJA V	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. ARULMURUGAN L ECE
7376241EC510	KALAIVENDHAN P	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. ARULMURUGAN L ECE
7376241EC511	KAVIN RAJA M	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. ARULMURUGAN L ECE
7376241EC512	NAIMALOSHINI D	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. ARULMURUGAN L ECE
7376241EC514	NAVEEN KUMAR M	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. ARULMURUGAN L ECE
7376241EC515	NAVEEN V	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Dr. ARULMURUGAN L ECE
7376241EC517	NITHIN C	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. RAGAVI M ECE
7376241EC518	PRANAV U P	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. RAGAVI M ECE
7376241EC519	RAMESH R	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. RAGAVI M ECE
7376241EC520	SANJEEV S	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. RAGAVI M ECE
7376241EC522	YASWANTH D	B. E.	ELECTRONICS AND COMMUNICATION ENGINEERING	Mrs. RAGAVI M ECE
`;

async function run() {
    const c = await mysql.createConnection({
        host: 'localhost',
        user: 'root',
        password: 'root',
        database: 'academic_forecast'
    });

    console.log('Fetching faculties for matching...');
    const [faculties] = await c.query('SELECT u.id, u.name FROM users u WHERE u.role = "faculty" OR u.role = "Faculty"');
    const facultyMap = {};
    faculties.forEach(f => {
        const cleanName = f.name.replace(/^(Mr\.|Mrs\.|Dr\.)\s+/i, '').replace(/\s+/g, ' ').trim().toUpperCase();
        facultyMap[cleanName] = f.id;
    });

    const lines = fullStudentsRaw.trim().split('\n');
    const hashedPassword = await bcrypt.hash('student123', 10);

    for (const line of lines) {
        const parts = line.split('\t');
        if (parts.length < 5) continue;
        
        const regNo = parts[0].trim();
        const name = parts[1].trim();
        const dept = parts[3].trim();
        const facultyRaw = parts[4].trim();
        
        const cleanFacName = facultyRaw.replace(/^(Mr\.|Mrs\.|Dr\.)\s+/i, '').replace(/\s+/g, ' ').replace(/\s+ECE$|\s+AIDS$/i, '').trim().toUpperCase();
        let facultyId = facultyMap[cleanFacName];
        
        if (!facultyId) {
            for (let dbName in facultyMap) {
                if (dbName.includes(cleanFacName) || cleanFacName.includes(dbName)) {
                    facultyId = facultyMap[dbName];
                    break;
                }
            }
        }

        try {
            // Check if user exists first
            const [existing] = await c.query('SELECT id FROM users WHERE email = ?', [`${regNo.toLowerCase()}@student.com`]);
            let userId;

            if (existing.length > 0) {
                userId = existing[0].id;
                await c.query('UPDATE users SET name = ? WHERE id = ?', [name, userId]);
            } else {
                const [userRes] = await c.query(
                    'INSERT INTO users (name, email, password, role) VALUES (?, ?, ?, ?)',
                    [name, `${regNo.toLowerCase()}@student.com`, hashedPassword, 'student']
                );
                userId = userRes.insertId;
            }

            const gpa = (Math.random() * (8.5 - 6.5) + 6.5).toFixed(2);
            await c.query(
                'INSERT INTO students (id, name, register_number, department, semester, previousGPA, faculty_id) VALUES (?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE name = VALUES(name), department = VALUES(department), semester = VALUES(semester), faculty_id = VALUES(faculty_id)',
                [userId, name, regNo, dept, 6, gpa, facultyId]
            );

            // Create past performance if not exists
            const [perfRows] = await c.query('SELECT id FROM past_performance WHERE student_id = ?', [userId]);
            if (perfRows.length === 0) {
                let currentGpa = parseFloat(gpa);
                for (let sem = 1; sem <= 5; sem++) {
                    const change = (Math.random() * 0.4 - 0.2);
                    currentGpa = Math.min(10, Math.max(5, currentGpa + change));
                    await c.query(
                        'INSERT INTO past_performance (student_id, semester, gpa) VALUES (?, ?, ?)',
                        [userId, sem, currentGpa.toFixed(2)]
                    );
                }
            }
            console.log(`Processed: ${regNo} -> ${facultyId ? 'Mapped to ID ' + facultyId : 'UNMATCHED: ' + facultyRaw}`);
        } catch (err) {
            console.error(`Error processing ${regNo}:`, err.message);
        }
    }

    console.log('Final student-faculty mapping import finished.');
    await c.end();
}

run();
